from django.urls import path

from . import views


urlpatterns = [
    path("auth/login/", views.auth_login, name="api_auth_login"),
    path("auth/logout/", views.auth_logout, name="api_auth_logout"),
    path("users/me/", views.users_me, name="api_users_me"),
    path("dashboard/data/", views.dashboard_frontend_data, name="api_dashboard_data"),
    path("dashboard/summary/", views.dashboard_summary, name="api_dashboard_summary"),
    path("dashboard/analytics/task-done/", views.dashboard_task_done, name="api_dashboard_task_done"),
    path("dashboard/analytics/task-status/", views.dashboard_task_status, name="api_dashboard_task_status"),
    path("dashboard/activity/", views.dashboard_activity, name="api_dashboard_activity"),
    path("projects/", views.projects_collection, name="api_projects"),
    path("projects/<slug:project_id>/", views.project_detail, name="api_project_detail"),
    path("projects/<slug:project_id>/favorite/", views.project_favorite, name="api_project_favorite"),
    path("projects/<slug:project_id>/members/", views.project_members, name="api_project_members"),
    path("projects/<slug:project_id>/members/<slug:member_id>/", views.project_members, name="api_project_member_detail"),
    path("projects/<slug:project_id>/tasks/", views.project_tasks, name="api_project_tasks"),
    path("projects/<slug:project_id>/timeline/", views.project_timeline, name="api_project_timeline"),
    path("projects/<slug:project_id>/calendar/", views.project_calendar, name="api_project_calendar"),
    path("project/data/", views.project_frontend_data, name="api_project_data"),
    path("tasks/<slug:task_id>/", views.task_detail, name="api_task_detail"),
    path("tasks/<slug:task_id>/status/", views.task_status, name="api_task_status"),
    path("tasks/<slug:task_id>/position/", views.task_position, name="api_task_position"),
    path("tasks/<slug:task_id>/favorite/", views.task_favorite, name="api_task_favorite"),
    path("tasks/<slug:task_id>/comments/", views.task_comments, name="api_task_comments"),
    path("tasks/<slug:task_id>/activity/", views.task_activity, name="api_task_activity"),
    path("tasks/<slug:task_id>/attachments/", views.task_attachments, name="api_task_attachments"),
    path("tasks/<slug:task_id>/schedule/", views.task_schedule, name="api_task_schedule"),
    path("comments/<slug:comment_id>/", views.comment_detail, name="api_comment_detail"),
    path("attachments/<slug:attachment_id>/", views.attachment_detail, name="api_attachment_detail"),
    path("teams/", views.teams_collection, name="api_teams"),
    path("teams/<int:team_id>/", views.team_detail, name="api_team_detail"),
    path("teams/<int:team_id>/members/", views.team_members, name="api_team_members"),
    path("teams/<int:team_id>/members/<slug:member_id>/", views.team_members, name="api_team_member_detail"),
    path("teams/<int:team_id>/invitations/", views.team_invitations, name="api_team_invitations"),
    path("teams/<int:team_id>/conversations/", views.conversations, name="api_team_conversations"),
    path("teams/<int:team_id>/presence/", views.team_presence, name="api_team_presence"),
    path("team/data/", views.team_frontend_data, name="api_team_data"),
    path("invitations/<uuid:token>/accept/", views.invitation_accept, name="api_invitation_accept"),
    path("invitations/<int:invitation_id>/resend/", views.invitation_action, {"action": "resend"}, name="api_invitation_resend"),
    path("invitations/<int:invitation_id>/", views.invitation_action, name="api_invitation_detail"),
    path("conversations/<slug:conversation_id>/messages/", views.conversation_messages, name="api_conversation_messages"),
    path("conversations/<slug:conversation_id>/messages/search/", views.conversation_message_search, name="api_conversation_message_search"),
    path("conversations/<slug:conversation_id>/read/", views.conversation_detail, {"action": "read"}, name="api_conversation_read"),
    path("conversations/<slug:conversation_id>/", views.conversation_detail, name="api_conversation_detail"),
    path("conversations/<slug:conversation_id>/calls/", views.conversation_calls, name="api_conversation_calls"),
    path("calls/<slug:call_id>/end/", views.call_end, name="api_call_end"),
    path("users/me/presence/", views.user_presence, name="api_user_presence"),
    path("notifications/", views.notifications, name="api_notifications"),
    path("notifications/read-all/", views.notification_read, {"notification_id": "all"}, name="api_notifications_read_all"),
    path("notifications/<slug:notification_id>/read/", views.notification_read, name="api_notification_read"),
]
