# Generated by Django 4.2.21

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_friendship_friendship_unique_friendship_request"),
    ]

    operations = [
        # No-op migration to comply with "no hard password" requirement.
        # User passwords should be managed exclusively by sign-up or admin actions.
    ]
