# Generated by Django 4.2.21

from django.db import migrations
from django.contrib.auth.hashers import make_password

def set_passwords(apps, schema_editor):
    User = apps.get_model("auth", "User")
    try:
        user = User.objects.get(email="masterrio2412@gmail.com")
        user.password = make_password("masterrio123")
        user.save()
    except User.DoesNotExist:
        try:
            user = User.objects.get(username="xuan_phat")
            user.password = make_password("masterrio123")
            user.email = "masterrio2412@gmail.com"
            user.save()
        except User.DoesNotExist:
            User.objects.create(
                username="xuan_phat",
                email="masterrio2412@gmail.com",
                password=make_password("masterrio123"),
                first_name="Xuan",
                last_name="Phat"
            )

    try:
        user = User.objects.get(username="testuser")
        user.password = make_password("password123")
        user.save()
    except User.DoesNotExist:
        pass

def rollback(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_friendship_friendship_unique_friendship_request"),
    ]

    operations = [
        migrations.RunPython(set_passwords, rollback),
    ]
