# Generated by Django 4.2.21 on 2026-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_project_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="positions",
            field=models.CharField(
                default="Member",
                help_text="Comma-separated positions/roles in workspace",
                max_length=255,
            ),
        ),
    ]
