# Generated by Codex on 2026-06-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_teammember_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.project",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start",
            field=models.FloatField(default=9),
        ),
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="row",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
