# Generated by Codex on 2026-06-22

from django.db import migrations, models
import django.db.models.deletion


class AddFieldIfNotExists(migrations.AddField):
    """Skip the database add when a local MySQL column already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)

        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor,
                    model._meta.db_table,
                )
            }

        if field.column in existing_columns:
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_teammember_positions"),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.project",
            ),
        ),
        AddFieldIfNotExists(
            model_name="task",
            name="start",
            field=models.FloatField(default=9),
        ),
        AddFieldIfNotExists(
            model_name="task",
            name="duration",
            field=models.FloatField(default=1),
        ),
        AddFieldIfNotExists(
            model_name="task",
            name="row",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("review", "Review"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
