# Generated by Django 4.2.21 on 2026-06-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_options_remove_task_start_task_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.FloatField(default=9.0),
        ),
    ]
