# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
